### ISSUE TITLE
Support restore for non-prysm clients

### ISSUE THREAD

**Issue by zktaiga** [AvadoDServer/AVADO-DNP-Rocketpool#42]
Currently, the following snippet is in use by the restore function: https://github.com/AvadoDServer/AVADO-DNP-Rocketpool/blob/1334ddf1928cc6dce68b9b1f413fe0e67aa9799c/build/monitor/server.js#L219-L221

This means it's not really possible to restore unless you are running Prysm as the CL.

**Comment by heeckhau** [comment]
The original backup contains files for all clients. This is just a sanity check that the uploaded file is indeed a RocketPool backup.
